In [28]:
import math
import scipy.linalg
import numpy as np

f = lambda x: math.sin(x / 5) * math.exp(x / 10) + 5*math.exp(-x / 2)

a = np.array([[1 for i in range(4, 7)] for j in range(0, 3)])
b = np.array([f(1), f(15), f(2)])

#a = np.array([[3,2,0],[1,-1,0],[0,5,1]])
#b = np.array([2,4,-1])

print(a)
print(b)

x = scipy.linalg.solve(a,b)
print(x)

#rint(scipy.linalg.solve(a, b))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[ 1.83939721  0.38528127  1.83939721]


LinAlgError: Matrix is singular.